version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
    - target: 3200
      published: 3200
      protocol: tcp
    volumes: 
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    deploy:
      replicas: 2 # This will deploy 2 copies of my application, no downtime while it builds.
  ao-main:
    image: ao # CHANGE THIS for front end access.
    build: .
    ports: 
    - target: 80
      published: 80
    deploy:
      replicas: 2